src/main/java/cn/nukkit/event/entity/EntityEffectRemoveEvent.java, src/main/java/cn/nukkit/event/entity/EntityEffectUpdateEvent.java, src/main/java/cn/nukkit/potion/Effect.java
PNX PR #260
https://github.com/PowerNukkitX/PowerNukkitX/pull/260
Related to #22
=> PNX PR #260

src/main/java/cn/nukkit/Player.java, src/main/java/cn/nukkit/event/player/PlayerMissedSwingEvent.java, src/main/java/cn/nukkit/network/protocol/types/AuthInputAction.java
Since 1.20.10 we need to send this sound to the players
=> Added handling of MISSED_SWING action

src/main/java/cn/nukkit/block/Block.java, src/main/java/cn/nukkit/block/BlockBubbleColumn.java, src/main/java/cn/nukkit/block/BlockID.java, src/main/java/cn/nukkit/block/BlockMagma.java, src/main/java/cn/nukkit/block/BlockSoulSand.java, src/main/java/cn/nukkit/entity/EntityLiving.java, src/main/java/cn/nukkit/event/entity/EntityDamageEvent.java
Add Bubble Column
From PowernukkitX
=> Add Bubble Column

src/main/java/cn/nukkit/Player.java, src/main/java/cn/nukkit/entity/Entity.java, src/main/java/cn/nukkit/entity/EntityHuman.java, src/main/java/cn/nukkit/event/player/PlayerToggleCrawlEvent.java, src/main/java/cn/nukkit/network/protocol/PlayerActionPacket.java, src/main/java/cn/nukkit/network/protocol/StartGamePacket.java
``` java
Add hunger change for jump while sneaking
Modify sneak speed // 75% normal speed
Modify Eyeheight & height // Correct values are from WaterdogPE
Change bounding box while sneaking
Add Basic Methods & Events for Crawling
// Crawling should be implemented by modifying several things like BlockTrapDoor.
// But here we are only talking about fixing sneaking
```
目前如上的功能均经过测试，可以通过潜行，缩小自身体积，进入1.5格的空间。
=> Basic Sneak Enhancement

src/main/java/cn/nukkit/block/BlockDispenser.java, src/main/java/cn/nukkit/block/BlockDropper.java, src/main/java/cn/nukkit/dispenser/DefaultDispenseBehavior.java
=> fix droppers

src/main/java/cn/nukkit/level/biome/impl/beach/BeachBiome.java, src/main/java/cn/nukkit/level/biome/impl/desert/DesertBiome.java, src/main/java/cn/nukkit/level/biome/impl/river/RiverBiome.java, src/main/java/cn/nukkit/level/biome/impl/swamp/SwampBiome.java, src/main/java/cn/nukkit/level/generator/populator/impl/PopulatorSugarcane.java
Values are from wiki and may require more testing
=> Improvement PopulatorSugarcane

src/main/java/cn/nukkit/item/ItemFirework.java
Related to #103 
Just made some deletions umm...
=> Fix the issue that firework default possesses the creeper explosion type

src/main/java/cn/nukkit/Server.java
=> fix: NullPointerException in WhitelistCommand

src/main/resources/lang/chs/lang.ini
=> Lang Chinese Simplified Updated

src/main/java/cn/nukkit/Player.java, src/main/java/cn/nukkit/inventory/transaction/EnchantTransaction.java
=> Attempt to fix enchanting ui destroying

src/main/java/cn/nukkit/event/level/WeatherChangeEvent.java, src/main/java/cn/nukkit/level/Level.java
=> add RainingIntensity

src/main/java/cn/nukkit/level/Level.java
=> fix: lighting bolt chance

src/main/java/cn/nukkit/level/particle/Particle.java
https://github.com/pmmp/BedrockProtocol/blob/master/src/types/ParticleIds.php
=> Fix DustParticle & MobSpellParticle enum

src/main/java/cn/nukkit/entity/mob/EntitySnowGolem.java, src/main/java/cn/nukkit/level/BlockPalette.java, src/main/java/cn/nukkit/level/DimensionData.java, src/main/java/cn/nukkit/level/GlobalBlockPalette.java, src/main/java/cn/nukkit/level/Level.java, src/main/java/cn/nukkit/level/format/Chunk.java, src/main/java/cn/nukkit/level/format/FullChunk.java, src/main/java/cn/nukkit/level/format/anvil/Anvil.java, src/main/java/cn/nukkit/level/format/anvil/Chunk.java, src/main/java/cn/nukkit/level/format/generic/BaseChunk.java, src/main/java/cn/nukkit/level/format/generic/BaseFullChunk.java, src/main/java/cn/nukkit/level/format/generic/serializer/NetworkChunkSerializer.java, src/main/java/cn/nukkit/level/util/BitArrayVersion.java, src/main/java/cn/nukkit/level/util/PalettedBlockStorage.java, src/main/java/cn/nukkit/nbt/stream/NBTInputStream.java, src/main/java/cn/nukkit/nbt/stream/NBTOutputStream.java, src/main/java/cn/nukkit/nbt/tag/ListTag.java, src/main/java/cn/nukkit/nbt/tag/Tag.java, src/main/java/cn/nukkit/utils/Utils.java
=> Prepare for 384 world heights and 3D biomes

src/main/java/cn/nukkit/resourcepacks/loader/ZippedResourcePackLoader.java
* Mostly from Easecation/Nukkit with few tweaks
References: 
https://github.com/EaseCation/Nukkit/commit/c4df1d630b49e06b7e6fe8dab3c7cd12ad8653b6
=> Add support for reading resource packs from directories

src/main/java/cn/nukkit/level/format/generic/serializer/NetworkChunkSerializer.java
=> Fix the problem of player coordinates in 1.12

src/main/java/cn/nukkit/entity/EntityHuman.java
=> fix: EntityHuman

src/main/java/cn/nukkit/block/Block.java, src/main/java/cn/nukkit/block/BlockShulkerBox.java, src/main/java/cn/nukkit/level/Level.java
If one shulker box with contents was broken by one player in creative, it should drop.
=> Fix ShulkerBox Drop

src/main/java/cn/nukkit/level/biome/BiomeSelector.java, src/main/java/cn/nukkit/level/biome/EnumBiome.java, src/main/java/cn/nukkit/level/biome/impl/ocean/ColdDeepOceanBiome.java, src/main/java/cn/nukkit/level/biome/impl/ocean/ColdOceanBiome.java, src/main/java/cn/nukkit/level/biome/impl/ocean/FrozenDeepOceanBiome.java, src/main/java/cn/nukkit/level/biome/impl/ocean/LukewarmDeepOceanBiome.java, src/main/java/cn/nukkit/level/biome/impl/ocean/LukewarmOceanBiome.java, src/main/java/cn/nukkit/level/biome/impl/ocean/NewFrozenOceanBiome.java, src/main/java/cn/nukkit/level/biome/impl/ocean/OceanBiome.java, src/main/java/cn/nukkit/level/biome/impl/ocean/WarmDeepOceanBiome.java, src/main/java/cn/nukkit/level/biome/impl/ocean/WarmOceanBiome.java, src/main/java/cn/nukkit/level/biome/impl/taiga/MegaSpruceTaigaHillsBiome.java, src/main/java/cn/nukkit/level/generator/populator/helper/EnsureCover.java, src/main/java/cn/nukkit/level/generator/populator/helper/PopulatorHelpers.java, src/main/java/cn/nukkit/level/generator/populator/impl/PopulatorKelp.java, src/main/java/cn/nukkit/level/generator/populator/impl/PopulatorSeagrass.java, src/main/java/cn/nukkit/level/generator/populator/impl/PopulatorUnderwaterFloor.java, src/main/java/cn/nukkit/level/generator/populator/type/PopulatorOceanFloorSurfaceBlock.java
Some code are from Nukkit leveldb branch.
=> feat: more biomes

.gitignore, src/main/java/cn/nukkit/block/BlockSlab.java, src/main/java/cn/nukkit/level/Level.java
https://github.com/user-attachments/assets/6c96f8ce-ccfe-4912-ac76-8b4e98a839b7
https://github.com/user-attachments/assets/e5351d8f-7bfe-4aec-9199-45a860f72c89
=> Fix Slab duplicate when placed on the top of a block

src/main/java/cn/nukkit/block/BlockChest.java, src/main/java/cn/nukkit/block/BlockLiquid.java, src/main/java/cn/nukkit/entity/item/EntityItem.java, src/main/java/cn/nukkit/entity/item/EntityVehicle.java, src/main/java/cn/nukkit/level/Level.java
- Fixed EntityItem, EntityVehicle & BlockHash for 384-height leveldb levels
=> fix: 384 height

src/main/java/cn/nukkit/Player.java, src/main/java/cn/nukkit/block/Block.java
Ported from PowerNukkitX-Legacy
=> feat: mining speed improvements

src/main/java/cn/nukkit/block/BlockPotato.java, src/main/java/cn/nukkit/item/food/Food.java
- Now it drops poisonous potato with 2% chance as in vanila
=> fix: potato drop

src/main/java/cn/nukkit/Server.java, src/main/java/cn/nukkit/entity/item/EntityPainting.java, src/main/java/cn/nukkit/item/ItemPainting.java
- Added all 1.21 paintings
- Added enable-new-paintings option in server.properties
=> feat: 1.21 paintings

src/main/java/cn/nukkit/level/format/leveldb/structure/LevelDBChunkSection.java, src/main/java/cn/nukkit/network/protocol/PlayerListPacket.java
- Fixed PlayerListPacket causing abnormal client display
- Add 1.1 compatibility to leveldb world
=> [Multiversion] some 1.1.0 protocol fix

src/main/java/cn/nukkit/block/BlockPistonBase.java
Before:
https://youtu.be/hMkL41tWsig
After:
https://youtu.be/sxvZPRQ-SlM
=> fix: piston dupe

src/main/java/cn/nukkit/block/Block.java
=> fix breaking in water

src/main/java/cn/nukkit/block/Block.java, src/main/java/cn/nukkit/entity/item/EntityEndCrystal.java, src/main/java/cn/nukkit/event/block/BlockExplodeEvent.java, src/main/java/cn/nukkit/event/entity/EntityExplodeEvent.java, src/main/java/cn/nukkit/level/Explosion.java
Adapted code from PowerNukkitX with a few fixes.
=> feat: improved tnt

src/main/java/cn/nukkit/Player.java, src/main/java/cn/nukkit/inventory/Fuel.java, src/main/java/cn/nukkit/item/Item.java, src/main/resources/legacy_item_ids.json, src/main/resources/recipes649.json
I tested it locally, but it requires more testing.
=> Fix Missing Recipes

src/main/java/cn/nukkit/block/BlockRedstoneWire.java
Replaced canBePlacedOn from PNX
=> fix: canBePlacedOn #423

src/main/java/cn/nukkit/form/element/ElementDropdown.java, src/main/java/cn/nukkit/form/element/ElementInput.java, src/main/java/cn/nukkit/form/element/ElementLabel.java, src/main/java/cn/nukkit/form/element/ElementSlider.java, src/main/java/cn/nukkit/form/element/ElementStepSlider.java, src/main/java/cn/nukkit/form/element/ElementToggle.java
=> fix: ElementToggle should have tooltip option instead of ElementLabel
